language: cpp

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - lcov

script:
  - # Debug build with coverage
  - mkdir Build-Debug && cd Build-Debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -DEXL_ENABLE_TESTING=ON -DEXL_ENABLE_COVERAGE=ON ..
  - cmake --build . --config Debug
  - ctest -C Debug --output-on-failure
  - cd ..
  - # Release build
  - mkdir Build-Release && cd Build-Release
  - cmake -DCMAKE_BUILD_TYPE=Release -DEXL_ENABLE_TESTING=ON ..
  - cmake --build . --config Release
  - ctest -C Release --output-on-failure
  - cd ..

after_success:
  - | # Collect coverage report
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        lcov --directory Build-Debug --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' "${PWD}"'/libs/*' "${PWD}"'/tests/*' --output-file coverage.info
        lcov --list coverage.info
        bash <(curl -s https://codecov.io/bash) -f coverage.info \
            || echo "Codecov did not collect coverage reports"
    fi
